// Code generated by ent, DO NOT EDIT.

package credential

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the credential type in the database.
	Label = "credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCredentialID holds the string denoting the credential_id field in the database.
	FieldCredentialID = "credential_id"
	// FieldAnchorID holds the string denoting the anchor_id field in the database.
	FieldAnchorID = "anchor_id"
	// FieldSchemaType holds the string denoting the schema_type field in the database.
	FieldSchemaType = "schema_type"
	// FieldHolderDid holds the string denoting the holder_did field in the database.
	FieldHolderDid = "holder_did"
	// FieldProofType holds the string denoting the proof_type field in the database.
	FieldProofType = "proof_type"
	// FieldCredentialData holds the string denoting the credential_data field in the database.
	FieldCredentialData = "credential_data"
	// FieldSignatureProof holds the string denoting the signature_proof field in the database.
	FieldSignatureProof = "signature_proof"
	// FieldIntegrityProof holds the string denoting the integrity_proof field in the database.
	FieldIntegrityProof = "integrity_proof"
	// FieldSparseMtProof holds the string denoting the sparse_mt_proof field in the database.
	FieldSparseMtProof = "sparse_mt_proof"
	// Table holds the table name of the credential in the database.
	Table = "credentials"
)

// Columns holds all SQL columns for credential fields.
var Columns = []string{
	FieldID,
	FieldCredentialID,
	FieldAnchorID,
	FieldSchemaType,
	FieldHolderDid,
	FieldProofType,
	FieldCredentialData,
	FieldSignatureProof,
	FieldIntegrityProof,
	FieldSparseMtProof,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SchemaTypeValidator is a validator for the "schema_type" field. It is called by the builders before save.
	SchemaTypeValidator func(string) error
	// HolderDidValidator is a validator for the "holder_did" field. It is called by the builders before save.
	HolderDidValidator func(string) error
)

// OrderOption defines the ordering options for the Credential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCredentialID orders the results by the credential_id field.
func ByCredentialID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialID, opts...).ToFunc()
}

// ByAnchorID orders the results by the anchor_id field.
func ByAnchorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnchorID, opts...).ToFunc()
}

// BySchemaType orders the results by the schema_type field.
func BySchemaType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchemaType, opts...).ToFunc()
}

// ByHolderDid orders the results by the holder_did field.
func ByHolderDid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHolderDid, opts...).ToFunc()
}
