// Code generated by ent, DO NOT EDIT.

package credential

import (
	"bloock-identity-managed-api/internal/platform/repository/sql/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Credential {
	return predicate.Credential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Credential {
	return predicate.Credential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Credential {
	return predicate.Credential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Credential {
	return predicate.Credential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Credential {
	return predicate.Credential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Credential {
	return predicate.Credential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Credential {
	return predicate.Credential(sql.FieldLTE(FieldID, id))
}

// CredentialID applies equality check predicate on the "credential_id" field. It's identical to CredentialIDEQ.
func CredentialID(v uuid.UUID) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialType applies equality check predicate on the "credential_type" field. It's identical to CredentialTypeEQ.
func CredentialType(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldCredentialType, v))
}

// IssuerDid applies equality check predicate on the "issuer_did" field. It's identical to IssuerDidEQ.
func IssuerDid(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldIssuerDid, v))
}

// HolderDid applies equality check predicate on the "holder_did" field. It's identical to HolderDidEQ.
func HolderDid(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldHolderDid, v))
}

// CredentialIDEQ applies the EQ predicate on the "credential_id" field.
func CredentialIDEQ(v uuid.UUID) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialIDNEQ applies the NEQ predicate on the "credential_id" field.
func CredentialIDNEQ(v uuid.UUID) predicate.Credential {
	return predicate.Credential(sql.FieldNEQ(FieldCredentialID, v))
}

// CredentialIDIn applies the In predicate on the "credential_id" field.
func CredentialIDIn(vs ...uuid.UUID) predicate.Credential {
	return predicate.Credential(sql.FieldIn(FieldCredentialID, vs...))
}

// CredentialIDNotIn applies the NotIn predicate on the "credential_id" field.
func CredentialIDNotIn(vs ...uuid.UUID) predicate.Credential {
	return predicate.Credential(sql.FieldNotIn(FieldCredentialID, vs...))
}

// CredentialIDGT applies the GT predicate on the "credential_id" field.
func CredentialIDGT(v uuid.UUID) predicate.Credential {
	return predicate.Credential(sql.FieldGT(FieldCredentialID, v))
}

// CredentialIDGTE applies the GTE predicate on the "credential_id" field.
func CredentialIDGTE(v uuid.UUID) predicate.Credential {
	return predicate.Credential(sql.FieldGTE(FieldCredentialID, v))
}

// CredentialIDLT applies the LT predicate on the "credential_id" field.
func CredentialIDLT(v uuid.UUID) predicate.Credential {
	return predicate.Credential(sql.FieldLT(FieldCredentialID, v))
}

// CredentialIDLTE applies the LTE predicate on the "credential_id" field.
func CredentialIDLTE(v uuid.UUID) predicate.Credential {
	return predicate.Credential(sql.FieldLTE(FieldCredentialID, v))
}

// CredentialTypeEQ applies the EQ predicate on the "credential_type" field.
func CredentialTypeEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldCredentialType, v))
}

// CredentialTypeNEQ applies the NEQ predicate on the "credential_type" field.
func CredentialTypeNEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldNEQ(FieldCredentialType, v))
}

// CredentialTypeIn applies the In predicate on the "credential_type" field.
func CredentialTypeIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldIn(FieldCredentialType, vs...))
}

// CredentialTypeNotIn applies the NotIn predicate on the "credential_type" field.
func CredentialTypeNotIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldNotIn(FieldCredentialType, vs...))
}

// CredentialTypeGT applies the GT predicate on the "credential_type" field.
func CredentialTypeGT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGT(FieldCredentialType, v))
}

// CredentialTypeGTE applies the GTE predicate on the "credential_type" field.
func CredentialTypeGTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGTE(FieldCredentialType, v))
}

// CredentialTypeLT applies the LT predicate on the "credential_type" field.
func CredentialTypeLT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLT(FieldCredentialType, v))
}

// CredentialTypeLTE applies the LTE predicate on the "credential_type" field.
func CredentialTypeLTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLTE(FieldCredentialType, v))
}

// CredentialTypeContains applies the Contains predicate on the "credential_type" field.
func CredentialTypeContains(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContains(FieldCredentialType, v))
}

// CredentialTypeHasPrefix applies the HasPrefix predicate on the "credential_type" field.
func CredentialTypeHasPrefix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasPrefix(FieldCredentialType, v))
}

// CredentialTypeHasSuffix applies the HasSuffix predicate on the "credential_type" field.
func CredentialTypeHasSuffix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasSuffix(FieldCredentialType, v))
}

// CredentialTypeEqualFold applies the EqualFold predicate on the "credential_type" field.
func CredentialTypeEqualFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEqualFold(FieldCredentialType, v))
}

// CredentialTypeContainsFold applies the ContainsFold predicate on the "credential_type" field.
func CredentialTypeContainsFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContainsFold(FieldCredentialType, v))
}

// IssuerDidEQ applies the EQ predicate on the "issuer_did" field.
func IssuerDidEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldIssuerDid, v))
}

// IssuerDidNEQ applies the NEQ predicate on the "issuer_did" field.
func IssuerDidNEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldNEQ(FieldIssuerDid, v))
}

// IssuerDidIn applies the In predicate on the "issuer_did" field.
func IssuerDidIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldIn(FieldIssuerDid, vs...))
}

// IssuerDidNotIn applies the NotIn predicate on the "issuer_did" field.
func IssuerDidNotIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldNotIn(FieldIssuerDid, vs...))
}

// IssuerDidGT applies the GT predicate on the "issuer_did" field.
func IssuerDidGT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGT(FieldIssuerDid, v))
}

// IssuerDidGTE applies the GTE predicate on the "issuer_did" field.
func IssuerDidGTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGTE(FieldIssuerDid, v))
}

// IssuerDidLT applies the LT predicate on the "issuer_did" field.
func IssuerDidLT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLT(FieldIssuerDid, v))
}

// IssuerDidLTE applies the LTE predicate on the "issuer_did" field.
func IssuerDidLTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLTE(FieldIssuerDid, v))
}

// IssuerDidContains applies the Contains predicate on the "issuer_did" field.
func IssuerDidContains(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContains(FieldIssuerDid, v))
}

// IssuerDidHasPrefix applies the HasPrefix predicate on the "issuer_did" field.
func IssuerDidHasPrefix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasPrefix(FieldIssuerDid, v))
}

// IssuerDidHasSuffix applies the HasSuffix predicate on the "issuer_did" field.
func IssuerDidHasSuffix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasSuffix(FieldIssuerDid, v))
}

// IssuerDidEqualFold applies the EqualFold predicate on the "issuer_did" field.
func IssuerDidEqualFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEqualFold(FieldIssuerDid, v))
}

// IssuerDidContainsFold applies the ContainsFold predicate on the "issuer_did" field.
func IssuerDidContainsFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContainsFold(FieldIssuerDid, v))
}

// HolderDidEQ applies the EQ predicate on the "holder_did" field.
func HolderDidEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldHolderDid, v))
}

// HolderDidNEQ applies the NEQ predicate on the "holder_did" field.
func HolderDidNEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldNEQ(FieldHolderDid, v))
}

// HolderDidIn applies the In predicate on the "holder_did" field.
func HolderDidIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldIn(FieldHolderDid, vs...))
}

// HolderDidNotIn applies the NotIn predicate on the "holder_did" field.
func HolderDidNotIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldNotIn(FieldHolderDid, vs...))
}

// HolderDidGT applies the GT predicate on the "holder_did" field.
func HolderDidGT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGT(FieldHolderDid, v))
}

// HolderDidGTE applies the GTE predicate on the "holder_did" field.
func HolderDidGTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGTE(FieldHolderDid, v))
}

// HolderDidLT applies the LT predicate on the "holder_did" field.
func HolderDidLT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLT(FieldHolderDid, v))
}

// HolderDidLTE applies the LTE predicate on the "holder_did" field.
func HolderDidLTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLTE(FieldHolderDid, v))
}

// HolderDidContains applies the Contains predicate on the "holder_did" field.
func HolderDidContains(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContains(FieldHolderDid, v))
}

// HolderDidHasPrefix applies the HasPrefix predicate on the "holder_did" field.
func HolderDidHasPrefix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasPrefix(FieldHolderDid, v))
}

// HolderDidHasSuffix applies the HasSuffix predicate on the "holder_did" field.
func HolderDidHasSuffix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasSuffix(FieldHolderDid, v))
}

// HolderDidEqualFold applies the EqualFold predicate on the "holder_did" field.
func HolderDidEqualFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEqualFold(FieldHolderDid, v))
}

// HolderDidContainsFold applies the ContainsFold predicate on the "holder_did" field.
func HolderDidContainsFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContainsFold(FieldHolderDid, v))
}

// SparseMtProofIsNil applies the IsNil predicate on the "sparse_mt_proof" field.
func SparseMtProofIsNil() predicate.Credential {
	return predicate.Credential(sql.FieldIsNull(FieldSparseMtProof))
}

// SparseMtProofNotNil applies the NotNil predicate on the "sparse_mt_proof" field.
func SparseMtProofNotNil() predicate.Credential {
	return predicate.Credential(sql.FieldNotNull(FieldSparseMtProof))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Credential) predicate.Credential {
	return predicate.Credential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Credential) predicate.Credential {
	return predicate.Credential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Credential) predicate.Credential {
	return predicate.Credential(sql.NotPredicates(p))
}
