BLOOCK_DB_CONNECTION_STRING: "file:bloock?mode=memory&cache=shared&_fk=1"
BLOOCK_API_KEY: "tFD-hh1QYTj1TQEp3LulhHAredSkekobuuZI8vduysc7sx2RZTdpnX6A5FSQuSvT"
BLOOCK_WEBHOOK_SECRET_KEY: "B2BeuSxClxzuBQp5BLnIldxJ9XdxbQUf"
BLOOCK_PUBLIC_HOST: "https://32a5-94-132-61-84.ngrok-free.app"
BLOOCK_LOCAL_PRIVATE_KEY: ""
BLOOCK_LOCAL_PUBLIC_KEY: ""
BLOOCK_MANAGED_KEY_ID: "a28493fc-2545-4fc6-bf56-552e7d43365c"
BLOOCK_API_HOST: "0.0.0.0"
BLOOCK_API_PORT: "8080"
BLOCK_API_DEBUG_MODE: true