api:
  host: "0.0.0.0"
  port: 8080
  debug_mode: false
  public_host: ""
  polygon_test_enabled: false

db:
  connection_string: "file:bloock?mode=memory&cache=shared&_fk=1"

auth:
  secret: ""

bloock:
  api_host: ""
  api_key: ""
  webhook_secret_key: ""

issuer:
  name: ""
  description: ""
  image: ""
  publish_interval: ""
  key:
    key: ""

verification:
  expiration: ""
