api:
  host: "0.0.0.0"
  port: 8080
  debug_mode: false
  public_host: ""

db:
  connection_string: "file:bloock?mode=memory&cache=shared&_fk=1"

bloock:
  api_host: ""
  api_key: ""
  webhook_secret_key: ""

blockchain:
  smart_contract: ""
  provider: ""
  resolver_prefix: ""

issuer:
  name: ""
  description: ""
  image: ""
  publish_interval: ""
  key:
    key: ""
  did_metadata:
    method: ""
    blockchain: ""
    network: ""
