services:
  bloock-identity-managed-api:
    image: bloock/identity-managed-api:latest
    container_name: bloock-identity-managed-api
    volumes:
      - ./config.yaml:/go/bin/config.yaml:ro
    ports:
      - 8080:8080
    environment:
      BLOOCK_BLOOCK_API_KEY: ""
        BLOOCK_BLOOCK_WEBHOOK_SECRET_KEY: ""
        BLOOCK_API_PUBLIC_HOST: ""