services:
  bloock-identity-managed-api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloock-identity-managed-api
    volumes:
      - ./config.yaml:/go/bin/config.yaml:ro
    ports:
      - 8080:8080
    environment:
      BLOOCK_DB_CONNECTION_STRING: "file:managed?mode=memory&cache=shared&_fk=1"
      BLOOCK_API_KEY: ""
      BLOOCK_WEBHOOK_URL: ""
      BLOOCK_WEBHOOK_SECRET_KEY: ""
      BLOOCK_API_HOST: "0.0.0.0"
      BLOOCK_API_PORT: "8080"
      BLOOCK_LOCAL_PRIVATE_KEY: ""
      BLOOCK_LOCAL_PUBLIC_KEY: ""
      BLOOCK_MANAGED_KEY_ID: ""
      BLOOCK_PUBLIC_HOST: ""
      BLOOCK_ENFORCE_TOLERANCE: false
      BLOOCK_POLYGON_PROVIDER: ""
      BLOOCK_ISSUER_DID_METHOD: ""
      BLOOCK_ISSUER_DID_BLOCKCHAIN: ""
      BLOOCK_ISSUER_DID_NETWORK: ""
      BLOOCK_API_DEBUG_MODE: false