services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: identity-managed
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 5s
      retries: 5

  bloock-identity-managed-api:
    image: bloock/identity-managed-api:latest
    container_name: bloock-identity-managed-api
    volumes:
      - ./config.yml:/go/bin/config.yml:ro
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      BLOOCK_BLOOCK_API_KEY: ""
      BLOOCK_BLOOCK_WEBHOOK_SECRET_KEY: ""
      BLOOCK_API_PUBLIC_HOST: ""
