services:
  mysql:
    container_name: mysql
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: identity-managed
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  bloock-identity-managed-api:
    image: bloock/identity-managed-api:latest
    container_name: bloock-identity-managed-api
    volumes:
      - ./config.yml:/go/bin/config.yml:ro
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      BLOOCK_DB_CONNECTION_STRING: "mysql://root:admin@tcp(mysql:3306)/identity-managed"
      BLOOCK_API_KEY: ""