// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CredentialsColumns holds the columns for the "credentials" table.
	CredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "credential_id", Type: field.TypeUUID},
		{Name: "anchor_id", Type: field.TypeInt64},
		{Name: "schema_type", Type: field.TypeString},
		{Name: "issuer_did", Type: field.TypeString},
		{Name: "holder_did", Type: field.TypeString},
		{Name: "proof_type", Type: field.TypeJSON, Nullable: true},
		{Name: "credential_data", Type: field.TypeJSON},
		{Name: "signature_proof", Type: field.TypeJSON},
		{Name: "integrity_proof", Type: field.TypeJSON, Nullable: true},
		{Name: "sparse_mt_proof", Type: field.TypeJSON, Nullable: true},
	}
	// CredentialsTable holds the schema information for the "credentials" table.
	CredentialsTable = &schema.Table{
		Name:       "credentials",
		Columns:    CredentialsColumns,
		PrimaryKey: []*schema.Column{CredentialsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "credential_credential_id",
				Unique:  true,
				Columns: []*schema.Column{CredentialsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CredentialsTable,
	}
)

func init() {
}
