// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/credential_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	domain "bloock-identity-managed-api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	go_iden3_core "github.com/iden3/go-iden3-core"
)

// MockCredentialRepository is a mock of CredentialRepository interface.
type MockCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialRepositoryMockRecorder
}

// MockCredentialRepositoryMockRecorder is the mock recorder for MockCredentialRepository.
type MockCredentialRepositoryMockRecorder struct {
	mock *MockCredentialRepository
}

// NewMockCredentialRepository creates a new mock instance.
func NewMockCredentialRepository(ctrl *gomock.Controller) *MockCredentialRepository {
	mock := &MockCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialRepository) EXPECT() *MockCredentialRepositoryMockRecorder {
	return m.recorder
}

// GetCredentialById mocks base method.
func (m *MockCredentialRepository) GetCredentialById(ctx context.Context, id uuid.UUID) (domain.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialById", ctx, id)
	ret0, _ := ret[0].(domain.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialById indicates an expected call of GetCredentialById.
func (mr *MockCredentialRepositoryMockRecorder) GetCredentialById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialById", reflect.TypeOf((*MockCredentialRepository)(nil).GetCredentialById), ctx, id)
}

// GetCredentialByIssuerAndId mocks base method.
func (m *MockCredentialRepository) GetCredentialByIssuerAndId(ctx context.Context, issuer *go_iden3_core.DID, id uuid.UUID) (domain.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialByIssuerAndId", ctx, issuer, id)
	ret0, _ := ret[0].(domain.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialByIssuerAndId indicates an expected call of GetCredentialByIssuerAndId.
func (mr *MockCredentialRepositoryMockRecorder) GetCredentialByIssuerAndId(ctx, issuer, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialByIssuerAndId", reflect.TypeOf((*MockCredentialRepository)(nil).GetCredentialByIssuerAndId), ctx, issuer, id)
}

// Save mocks base method.
func (m *MockCredentialRepository) Save(ctx context.Context, c domain.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCredentialRepositoryMockRecorder) Save(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCredentialRepository)(nil).Save), ctx, c)
}

// UpdateCertificationAnchor mocks base method.
func (m *MockCredentialRepository) UpdateCertificationAnchor(ctx context.Context, id uuid.UUID, proofs map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCertificationAnchor", ctx, id, proofs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCertificationAnchor indicates an expected call of UpdateCertificationAnchor.
func (mr *MockCredentialRepositoryMockRecorder) UpdateCertificationAnchor(ctx, id, proofs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCertificationAnchor", reflect.TypeOf((*MockCredentialRepository)(nil).UpdateCertificationAnchor), ctx, id, proofs)
}
