// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bloock-identity-managed-api/internal/platform/repository/sql/ent/credential"
	"bloock-identity-managed-api/internal/platform/repository/sql/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	credentialFields := schema.Credential{}.Fields()
	_ = credentialFields
	// credentialDescCredentialType is the schema descriptor for credential_type field.
	credentialDescCredentialType := credentialFields[2].Descriptor()
	// credential.CredentialTypeValidator is a validator for the "credential_type" field. It is called by the builders before save.
	credential.CredentialTypeValidator = credentialDescCredentialType.Validators[0].(func(string) error)
	// credentialDescHolderDid is the schema descriptor for holder_did field.
	credentialDescHolderDid := credentialFields[3].Descriptor()
	// credential.HolderDidValidator is a validator for the "holder_did" field. It is called by the builders before save.
	credential.HolderDidValidator = credentialDescHolderDid.Validators[0].(func(string) error)
}
